### ISSUE TITLE
Duplicate features?

### ISSUE THREAD

**Issue by dandv** [xolvio/Letterpress#10]
https://github.com/xolvio/Letterpress/tree/master/tests/cucumber/features has features but no steps. It's linked from the very end of the [Chimp tutorial](https://chimp.readme.io/docs/tutorial).

https://github.com/xolvio/Letterpress/tree/master/app/tests/cucumber/features has apparently the same features, but along with step definitions. Maybe the tutorial should link here? If a duplicate location must exist, maybe a symlink would be better?

**Comment by samhatoum** [comment]
You're right, this was done in error from Simian.io!

**Comment by samhatoum** [comment]
thank you
