### ISSUE TITLE
Unable to run application as per README instructions

### ISSUE THREAD

**Issue by andersr** [xolvio/Letterpress#16]
Hi - I am following the instructions in the README for running the application but am getting a 'command not found' message when typing 'run' in the root directory of the repo. Did I misunderstand the instructions?

<img width="607" alt="screen shot 2015-10-08 at 10 31 13 am" src="https://cloud.githubusercontent.com/assets/819213/10369369/e0d407ce-6da7-11e5-9973-96fe09d3de37.png">

**Update:**

This worked after I added this script to my $PATH (Eg ```export PATH=$PATH:~/path/to/Letterpress/repo```) although I can't imagine having to do that for every repo I want to run.  (Maybe change this to [use a node-based start script](https://www.eventedmind.com/classes/setting-up-meteor-projects/a-sample-start-script)?)

**Comment by sircharleswatson** [comment]
you should be able to run it if you type exactly: `./run` with the `./` included.

**Comment by andersr** [comment]
Tried that as well, but didn't work for me.

<img width="595" alt="screen shot 2015-10-09 at 2 13 37 am" src="https://cloud.githubusercontent.com/assets/819213/10387021/812d22a4-6e2b-11e5-8781-9c4b132c82d1.png">

**Comment by sircharleswatson** [comment]
@andersr you're right, that doesnt work. You have to add the `.sh` to it. like this `./run.sh`

@samhatoum @Sanjo I think it should be changed so that it doesnt have the .sh extension. as long as it's executable and has the right stuff at the top of the file, it'll work as currently stated in the README.

**Comment by andersr** [comment]
Yup, ```./run.sh``` worked for me.

**Comment by ghost** [comment]
Done
